# -*- coding: utf-8 -*-
"""data_loading.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xmg0-RmOZQQuGmNBU2fNwxOMpi-l_Lm8

# Carga de datos para el modelo

A continuación se presentan los pasos a seguir para descargar el dataframe que contiene los datos que se usarán en el modelo a implementar. Inicialmente, los datos se descargan de la página web [Kaggle](https://www.kaggle.com/deepu1109/star-dataset) a una máquina local. A continuación, dicho archivo se traslada a una carpeta de Google Drive, a la cual se tiene acceso público para descargar los datos directamente desde allí."""

"""Se importa la librería de gdown junto con pandas para manipular el dataframe en Python"""

import pandas as pd
import gdown

"""Se define ahora una función para realizar la carga de los datos de la carpeta de Drive, así mismo se le asocia un nombre a dicho archivo. Además, se carga lee el .csv con la librería de pandas y se guarda en un dataframe"""

def dataload(link, name):
    gdown.download(link, name, quiet=False)
    df = pd.read_csv(name)
    return df

"""El siguiente paso es hacer uso de la anterior función, para lo cual se presenta la url del archivo y se asocia con un nombre relacionado a la temática"""

link = 'https://drive.google.com/uc?export=download&id=1oOgj9f5UTITTDzMehEIIzNz2aoR2IlgZ'
name = 'stars.csv'
df_stars = dataload(link, name)

"""Finalmente, mostramos las primeras líneas de dicho dataframe para verificar que los datos fueron cargados correctamente"""

df_stars.head(5)